name: Deploy Static Content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # index.html 이 있는 폴더
          path: 'composeApp/src/webMain/resources'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4